const refbook = [
    { value: '00', label: '(00) "Fond" (letter reports "found"), no mention of the bird or its body in recovery report' },
    { value: '01', label: '(01) Found, bird or body mentioned in recovery letter' },
    { value: '02', label: '(02) Ring only found in circumstances where the bird could have endet ist life without transported information in the field' },
    { value: '03', label: '(03) Ring and leg only found in natural circumstances' },
    { value: '04', label: '(04) not used' },
    { value: '05', label: '(05) Code 05 is not used' },
    { value: '06', label: '(06) Found on ship unless there is further indication that the bird was caught in fishing gear, hit wires, attracted to lights ets' },
    { value: '07', label: '(07) Joined or attracted to domestic animals or birds' },
    { value: '08', label: '(08) Dead or seriously harmed by ringer through catching or handling processes' },
    { value: '09', label: '(09) Recovery caused by the ring or mark on the bird - this includes becoming entangled because of the ring and being recovered as a result of injuries caused by the ring' },
    { value: '10', label: '(10) Shot' },
    { value: '11', label: '(11) Found shot' },
    { value: '12', label: '(12) Shot to protect crops, foodstuffs, animals or game species' },
    { value: '13', label: '(13) Shot in the course of nature protection procedures' },
    { value: '14', label: '(14) Shot to protect human life' },
    { value: '15', label: '(15) Shot to provide plumage for decoration or commerce or shot as part of a scientific investigation' },
    { value: '16', label: '(16) Shot because it was ringed or marked' },
    { value: '17', label: '(17) not used' },
    { value: '18', label: '(18) not used' },
    { value: '19', label: '(19) Bird has been "hunted"and is likely to have been shot in the majority of cases rather than to have beer taken by other means' },
    { value: '20', label: '(20) Hunted, trapped, poisoned intentionally by man (NB: not shot)' },
    { value: '21', label: '(21) Trapped for caging' },
    { value: '22', label: '(22) Trapped, poisoned etc., to protect crops, foodstuffs, animals or game species' },
    { value: '23', label: '(23) Trapped, poisoned etc., during nature protection procedures' },
    { value: '24', label: '(24) Trapped, poisoned etc., to protect human life' },
    { value: '25', label: '(25) Trapped, poisoned etc., for plumage or during scientific investigation' },
    { value: '26', label: '(26) Trapped, poisoned etc., because it was ringed' },
    { value: '27', label: '(27) Found at or in nest-box or other structure specially placed or modified by man for birds to use' },
    { value: '28', label: '(28) Ring number of metal ring read in field without the bird being caught' },
    { value: '29', label: '(29) See primary division. 8' },
    { value: '30', label: '(30) Oil' },
    { value: '31', label: '(31) Contact withdiscarded human materias' },
    { value: '32', label: '(32) Contact with human artefacts which are still in use' },
    { value: '33', label: '(33) Entangled in crop protection nets' },
    { value: '34', label: '(34) Accidentally trapped where the intention was to trap other species of birds or vertebrates' },
    { value: '35', label: '(35) Electrocuted' },
    { value: '36', label: '(36) Radio-activity' },
    { value: '37', label: '(37) Poisoned through chemical pollution. Chemical identified (one or more may be involved) and details available from national ringing centre' },
    { value: '38', label: '(38) Poisoned through chemical pollution but identify of chemical agent (agents) not known' },
    { value: '40', label: '(40) Road' },
    { value: '41', label: '(41) Railway' },
    { value: '42', label: '(42) Aircraft' },
    { value: '43', label: '(43) Collision with (or presumed) THIN man-made structure-wires' },
    { value: '44', label: '(44) Collision with (or presumed) glass' },
    { value: '45', label: '(45) Collision with (or presumed) THICK man-made structure, building, bridge etc' },
    { value: '46', label: '(46) Entered man-made structure NOT built or modified to trap animals' },
    { value: '47', label: '(47) Attracted to lights' },
    { value: '48', label: '(48) Recovered as a result of active  human occupation' },
    { value: '49', label: '(49) Drowned in artificial water container' },
    { value: '50', label: '(50) Contusions, breaks, general trauma where no other cause given' },
    { value: '51', label: '(51) Malformations (congenital, mechanical (e.g. from broken bill) or from tumours)' },
    { value: '52', label: '(52) Fungal infections (e.g. aspergillosis etc.)' },
    { value: '53', label: '(53) Viral infections' },
    { value: '54', label: '(54) Bacterial infections (but see 56 below)' },
    { value: '55', label: '(55) Other endo-parasites (e.g. blood-parasites, nematodes, trematodes ets.)' },
    { value: '56', label: '(56) Botulism' },
    { value: '57', label: '(57) Red-tide (dinoflagellate poisoning)' },
    { value: '58', label: '(58) Combination of any of the above without definite single cause beig known' },
    { value: '59', label: '(59) Veterinary examination made and report available - no positive conclusions' },
    { value: '60', label: '(60) Taken by unspecified animal' },
    { value: '61', label: '(61)Taken by cat' },
    { value: '62', label: '(62) Taken by other domestic animal or one in captivity (e.g. farmed mink or zoo animals: includes poultry, reptiles etc. in captivity)' },
    { value: '63', label: '(63) Taken by wild or feral mammal (include escaped mink)' },
    { value: '64', label: '(64) Taken by owl or raptor -  exact identification of predator available' },
    { value: '65', label: '(65) Taken by owl or raptor -  exact identification of predator not known' },
    { value: '66', label: '(66) Taken by other species of bird (not conspecific)' },
    { value: '67', label: '(67) Taken by conspecific' },
    { value: '68', label: '(68) Taken by reptile, amphibian or fish' },
    { value: '69', label: '(69) Taken by other animals(e.g. wasps, ants bees, spiders etc)' },
    { value: '70', label: '(70) Drowned - note 49 if in an artificial' },
    { value: '71', label: '(71) Tangled in natural object' },
    { value: '72', label: '(72) In natural hole or cave' },
    { value: '73', label: '(73) Collided with any sort of natural object' },
    { value: '74', label: '(74) Poor condition with indication that cold weather was cause' },
    { value: '75', label: '(75) Poor condition with indication that hot weather was cause' },
    { value: '76', label: '(76)Poor condition, starvation' },
    { value: '77', label: '(77) Caught in ice' },
    { value: '78', label: '(78) Violent climatological phenomena' },
    { value: '80', label: '(80) Bird identified as an individual in the field by something else then the metal ring' },
    { value: '81', label: '(81) Bird identified from coloured or numbered legring(s)' },
    { value: '82', label: '(82) Bird identified from coloured or numbered neckring(s)' },
    { value: '83', label: '(83) Bird identified from wingtags' },
    { value: '84', label: '(84) Bird identified with radio tracking' },
    { value: '85', label: '(85) Bird identified with satellite tracking' },
    { value: '86', label: '(86)  Bird identified from transponder' },
    { value: '87', label: '(87)  Bird identified from nasal mack(s)' },
    { value: '88', label: '(88)  Bird identified from flight feather(s) stamped with the ringnumber' },
    { value: '89', label: '(89)  Bird identified from body- or wing painting' },
    { value: '99', label: '(99) No information at all, ring number written with no mention of the bird, wheter found, wheter dead or alive' },
]

export function getCircumstancesHuman(value) {
    const item = refbook.filter(item => item.value === value)[0]
    return item ? item.label : value
}
